### PR TITLE
15 style route line

### PR DESCRIPTION
**Pull request by devstorm21**
#15 completed. @mdiener21

### CODE REVIEW

**Comment by devstorm21** [comment]
@mdiener21 please merge the current requests so I can go forward.

**Comment by mdiener21** [comment]
@devstorm21  branch has conflicts with master, and is not working as expected, only shows dashed lines no solid line for current active floor

**Comment by devstorm21** [comment]
@mdiener21 please tell me the case which is not working as expected. You might not select any floor and there is still #24 remained. I will do #24 after you merge this.

**Comment by devstorm21** [comment]
@mdiener21  #15, #24 completed.

**Pull request merged**
